(specifications->manifest
    '("foot"
     "alacritty"
     "ranger"
     "tmux"
     "xclip"
     "guile"
     "nss-certs"
     "fontconfig"
     "glibc-locales"
     "ripgrep"
     "go-github-com-junegunn-fzf"
     "neovim"
     "fish"))
