# Configure i3-autodisplay
# go get github.com/lpicanco/i3-autodisplay/cmd/i3-autodisplay
# example config:
# displays:
#   - name: eDP1
#     workspaces: [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
#   - name: HDMI1
#     workspaces: [2, 4, 6, 8]
#     randr_extra_options: "--left-of eDP1"
#   - name: DP1
#     workspaces: [1, 3, 5, 7, 9]
#     randr_extra_options: "--left-of HDMI1"

displays:
  - name: eDP
    workspaces: [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
  - name: HDMI-A-0
    workspaces: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    randr_extra_options: "--left-of eDP"
  - name: DisplayPort-0
    workspaces: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    randr_extra_options: "--left-of eDP"
