[packages.apt]
packages = [
  "tmux",
  "sway",
  "swayidle",
  "swaylock",
  "swaybg",
  # general build dependencies
  "build-essential",
  "cmake",
  "bison",
  "flex",
  "meson",
  "ninja-build",
  "pkg-config",
  # git secret helper
  "libsecret-1-dev",
  # Animated backgreound
  "cbonsai",
  "gir1.2-gtklayershell",
  "libgtk-layer-shell0",
  "gir1.2-vte",
  "python3-gi",
  # cargo build dependencies & C bindings
  "libbz2-dev",
  "libdbus-1-dev",
  "liblzma-dev",
  "libpcap-dev",
  "libpulse-dev",
  "libsensors-dev",
  "libsqlite3-dev",
  "libssh2-1-dev",
  "libssl-dev",
  "zlib1g-dev",
  # dragon build dependencies
  "libgtk-3-dev",
  # rofi-wayland build dependencies
  "libcairo2-dev",
  "libgdk-pixbuf-2.0-dev",
  "libglib2.0-dev",
  "libpango1.0-dev",
  "libstartup-notification0-dev",
  "libwayland-dev",
  "libxcb1-dev",
  "libxcb-cursor-dev",
  "libxcb-ewmh-dev",
  "libxcb-icccm4-dev",
  "libxcb-keysyms1-dev",
  "libxcb-randr0-dev",
  "libxcb-util-dev",
  "libxcb-xinerama0-dev",
  "libxcb-xkb-dev",
  "libxkbcommon-dev",
  "libxkbcommon-x11-dev",
  "wayland-protocols",
]

[packages.brew]
packages = [
  "ripgrep",
]

[packages.cargo]
crates = [
  "atuin",
  "bandwhich",
  "cargo-updater",
  "engram_mcp",
  "eza",
  "fd-find",
  "git-delta",
  "jj-cli",
  "lazyjj",
  "mergiraf",
  "mise",
  "netscanner",
  "ntap",
  "ouch",
  "pay-respects",
  "pay-respects-module-runtime-rules",
  "ripgrep",
  "tree-sitter-cli",
  "yazi-build",
  "zoxide",
]
git_crates = [
  "https://github.com/gierdo/valv-cli.git",
  "https://github.com/Ataraxy-Labs/weave.git weave-cli",
  "https://github.com/Ataraxy-Labs/weave.git weave-driver",
  "https://github.com/greshake/i3status-rust.git i3status-rs --locked",
]

[packages.go]
packages = [
  "github.com/Gelio/go-global-update@latest",
  "github.com/bazelbuild/bazelisk@latest",
  "github.com/google/yamlfmt/cmd/yamlfmt@latest",
  "github.com/jesseduffield/lazydocker@latest",
  "github.com/pranshuparmar/witr/cmd/witr@latest",
  "golang.org/x/lint/golint@latest",
  "golang.org/x/tools/cmd/goimports@latest",
  "golang.org/x/tools/gopls@latest",
  "mvdan.cc/sh/v3/cmd/shfmt@latest",
]

[packages.npm]
packages = [
  "@1mcp/agent",
  "@bufbuild/buf",
  "@mistweaverco/kulala-ls",
  "bash-language-server",
  "bun",
  "concurrently",
  "copy",
  "cross-spawn",
  "dockerfile-language-server-nodejs",
  "esparse",
  "fixjson",
  "http-signature",
  "init-package-json",
  "js-yaml",
  "libcipm",
  "libnpmpublish",
  "lstat",
  "mkdirp",
  "neovim",
  "node-gyp",
  "normalize-package-data",
  "prettier",
  "rimraf",
  "shellcheck",
  "typescript",
  "typescript-language-server",
  "vscode-languageserver",
  "which",
  "yaml-language-server",
  "yarn",
]

[packages.uv]
tools = [
  "autopep8",
  "black",
  "cfn-lint",
  "debugpy",
  "flake8",
  "git+https://github.com/oraios/serena",
  "keyring",
  "podman-compose",
  "poetry",
  "pylint",
  "pysentry-rs",
  "pytype",
  "virtualenv",
  "visidata",
]

[packages.yazi]
plugins = [
  "gierdo/valv-cli:valv",
  "ndtoan96/ouch",
  "yazi-rs/plugins:chmod",
  "yazi-rs/plugins:full-border",
  "yazi-rs/plugins:git",
  "yazi-rs/plugins:mime-ext",
  "yazi-rs/plugins:mount",
]

[packages.fonts]
nerdfonts = [
  "0xProto",
  "3270",
  "Agave",
  "AnonymousPro",
  "Arimo",
  "AurulentSansMono",
  "BigBlueTerminal",
  "BitstreamVeraSansMono",
  "CascadiaCode",
  "CascadiaMono",
  "CodeNewRoman",
  "ComicShannsMono",
  "CommitMono",
  "Cousine",
  "D2Coding",
  "DaddyTimeMono",
  "DejaVuSansMono",
  "DepartureMono",
  "DroidSansMono",
  "EnvyCodeR",
  "FantasqueSansMono",
  "FiraCode",
  "FiraMono",
  "GeistMono",
  "Go-Mono",
  "Gohu",
  "Hack",
  "Hasklig",
  "HeavyData",
  "Hermit",
  "IBMPlexMono",
  "Inconsolata",
  "InconsolataGo",
  "InconsolataLGC",
  "IntelOneMono",
  "Iosevka",
  "IosevkaTerm",
  "IosevkaTermSlab",
  "JetBrainsMono",
  "Lekton",
  "LiberationMono",
  "Lilex",
  "MPlus",
  "MartianMono",
  "Meslo",
  "Monaspace",
  "Monofur",
  "Monoid",
  "Mononoki",
  "Noto",
  "OpenDyslexic",
  "Overpass",
  "ProFont",
  "ProggyClean",
  "Recursive",
  "RobotoMono",
  "ShareTechMono",
  "SourceCodePro",
  "SpaceMono",
  "Terminus",
  "Tinos",
  "Ubuntu",
  "UbuntuMono",
  "UbuntuSans",
  "VictorMono",
  "ZedMono",
  "iA-Writer",
]
