[[jobs]]
name = "install tpm"
type = "git"
clone = true
dest = "{{ home_dir }}/.tmux/plugins/tpm"
repo = "https://github.com/tmux-plugins/tpm"


[[jobs]]
name = "i3status-rust: repository"
type = "git"
clone = true
dest = "{{ home_dir }}/workspace/other/i3status-rust"
repo = "https://github.com/greshake/i3status-rust.git"

[[jobs]]
name = "i3status-rust: install"
needs = ["i3status-rust: repository"]
type = "command"
chdir = "{{ home_dir }}/workspace/other/i3status-rust"
command = "cargo"
argv = ["install", "--path", ".", "--locked"]


[[jobs]]
name = "dragon: repository"
type = "git"
clone = true
dest = "{{ home_dir }}/workspace/other/dragon"
repo = "https://github.com/mwh/dragon.git"

[[jobs]]
name = "dragon: install"
needs = ["dragon: repository"]
type = "bash"
chdir = "{{ home_dir }}/workspace/other/i3status-rust"
command = "bash"
argv = [
  "-c",
  'make && make install'
]


[[jobs]]
name = "rofi-wayland: repository"
type = "git"
clone = true
dest = "{{ home_dir }}/workspace/other/rofi"
repo = "https://github.com/lbonn/rofi.git"


[[jobs]]
type = "installergo"
name = "Install go dependencies"
packages = [
  "mvdan.cc/sh/v3/cmd/shfmt",
  "gitlab.com/gitlab-org/cli/cmd/glab",
  "mvdan.cc/sh/v3/cmd/shfmt",
  "golang.org/x/tools/gopls",
  "golang.org/x/lint/golint",
  "golang.org/x/tools/cmd/goimports",
]
state = "latest"


[[jobs]]
name = "install npm dependencies"
type = "installernpm"
packages = [
  "yarn",
  "neovim",
  "rimraf",
  "copy",
  "concurrently",
  "libcipm",
  "esparse",
  "normalize-package-data",
  "js-yaml",
  "mkdirp",
  "init-package-json",
  "http-signature",
  "lstat",
  "which",
  "cross-spawn",
  "libnpmpublish",
  "node-gyp",
  "dockerfile-language-server-nodejs",
  "typescript",
  "typescript-language-server",
  "yaml-language-server",
  "vscode-languageserver",
  "bash-language-server",
  "prettier",
  "shellcheck"
]
state = "present"


[[jobs]]
name = "install python dependencies"
type = "command"
command = "pip3"
argv = [
  "install",
  "--user",
  "--upgrade",
  "poetry",
  "thefuck",
  "pylint",
  "flake8",
  "pyright",
  "pynvim",
  "black",
  "jedi-language-server",
  "bandit",
  "cfn-lint"
]


[[jobs]]
name = "install rust dependencies"
type = "installercargo"
crates = [
  "atuin",
  "git-delta",
  "ripgrep",
  "fd-find",
]
state = "present"


[[jobs]]
name = "install aws cli v2"
type = "command"
command = "bash"
argv = [
  "-c",
  'mkdir -p ~/Downloads/awscli && cd ~/Downloads/awscli && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && ./aws/install -i ~/.local/aws-cli -b ~/.local/bin --update && cd && rm -rf ~/Downloads/awscli'
]
