[[jobs]]
name = "install tpm"
type = "git"
clone = true
dest = "{{ home_dir }}/.tmux/plugins/tpm"
repo = "https://github.com/tmux-plugins/tpm"


[[jobs]]
name = "i3status-rust: repository"
type = "git"
clone = true
dest = "{{ home_dir }}/workspace/other/i3status-rust"
repo = "https://github.com/greshake/i3status-rust.git"

[[jobs]]
name = "i3status-rust: install"
needs = ["i3status-rust: repository"]
type = "command"
chdir = "{{ home_dir }}/workspace/other/i3status-rust"
command = "cargo"
argv = ["install", "--path", ".", "--locked"]


[[jobs]]
name = "dragon: repository"
type = "git"
clone = true
dest = "{{ home_dir }}/workspace/other/dragon"
repo = "https://github.com/mwh/dragon.git"

[[jobs]]
name = "dragon: install"
needs = ["dragon: repository"]
type = "command"
chdir = "{{ home_dir }}/workspace/other/dragon"
command = "bash"
argv = [
  "-c",
  'make && make install'
]
when = "{{ not has_executable(exe='dragon') }}"


[[jobs]]
name = "rofi-wayland: repository"
type = "git"
clone = true
dest = "{{ home_dir }}/workspace/other/rofi"
repo = "https://github.com/lbonn/rofi.git"

[[jobs]]
name = "rofi-wayland: install"
needs = ["rofi-wayland: repository"]
type = "command"
chdir = "{{ home_dir }}/workspace/other/rofi"
command = "bash"
argv = [
  "-c",
  'meson setup build --prefix ${HOME}/.local && cd build && ninja install'
]
when = "{{ not has_executable(exe='rofi') }}"


[[jobs]]
type = "installergo"
name = "Install go dependencies"
packages = [
  "github.com/google/yamlfmt/cmd/yamlfmt",
  "mvdan.cc/sh/v3/cmd/shfmt",
  "gitlab.com/gitlab-org/cli/cmd/glab",
  "github.com/Gelio/go-global-update",
  "mvdan.cc/sh/v3/cmd/shfmt",
  "golang.org/x/tools/gopls",
  "golang.org/x/lint/golint",
  "golang.org/x/tools/cmd/goimports",
]
state = "latest"


[[jobs]]
name = "install npm dependencies"
type = "installernpm"
packages = [
  "bash-language-server",
  "concurrently",
  "copy",
  "cross-spawn",
  "dockerfile-language-server-nodejs",
  "esparse",
  "fixjson",
  "http-signature",
  "init-package-json",
  "js-yaml",
  "libcipm",
  "libnpmpublish",
  "lstat",
  "mkdirp",
  "neovim",
  "node-gyp",
  "normalize-package-data",
  "prettier",
  "rimraf",
  "shellcheck",
  "typescript",
  "typescript-language-server",
  "vscode-languageserver",
  "which",
  "yaml-language-server",
  "yarn",
]
state = "present"


[[jobs]]
name = "install python dependencies"
type = "command"
command = "pip3"
argv = [
  "install",
  "--user",
  "--upgrade",
  "poetry",
  "thefuck",
  "pylint",
  "flake8",
  "pyright",
  "pynvim",
  "debugpy",
  "black",
  "autopep8",
  "jedi-language-server",
  "bandit",
  "cfn-lint"
]
state = "present"


[[jobs]]
name = "install rust dependencies"
type = "installercargo"
crates = [
  "atuin",
  "cargo-updater",
  "git-delta",
  "ripgrep",
  "fd-find",
]
state = "present"


[[jobs]]
name = "install neovim"
type = "command"
command = "bash"
argv = [
  "-c",
  '''\
  asdf plugin-add neovim \
  && asdf install neovim latest \
  && asdf global neovim latest
  '''
]
when = "{{ has_executable(exe='asdf') }}"


[[jobs]]
name = "install aws cli v2"
type = "command"
command = "bash"
argv = [
  "-c",
  '''\
  mkdir -p ~/Downloads/awscli \
  && cd ~/Downloads/awscli \
  && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
  && unzip awscliv2.zip \
  && ./aws/install -i ~/.local/aws-cli -b ~/.local/bin --update \
  && cd \
  && rm -rf ~/Downloads/awscli \
  '''
]
when = "{{ not has_executable(exe='aws') }}"


[[jobs]]
name = "install git credential helper"
type = "command"
command = "bash"
argv = [
  "-c",
  '''\
  mkdir -p ~/workspace/other/libsecret \
  && cd ~/workspace/other/libsecret \
  && cp -r /usr/share/doc/git/contrib/credential/libsecret/* ./ \
  && make \
  && mkdir -p ~/.local/bin \
  && cp git-credential-libsecret ~/.local/bin \
  '''
]
when = "{{ not has_executable(exe='git-credential-libsecret') }}"
