[[jobs]]
name = "install nerd-fonts"
type = "command"
chdir = "{{ home_dir }}/.dotfiles/gists"
command = "bash"
argv = [
  "-c",
  './install-nerd-fonts.sh'
]


[[jobs]]
name = "set-up gtk theme"
type = "command"
chdir = "{{ home_dir }}/.dotfiles/gists"
command = "bash"
argv = [
  "-c",
  './install-solarized-theme.sh'
]


[[jobs]]
name = "install llama models"
type = "command"
chdir = "{{ home_dir }}/.dotfiles/gists"
command = "bash"
argv = [
  "-c",
  './install-llama-models.sh'
]
