[[jobs]]
name = "nerd-fonts: repository"
type = "git"
depth = 1
clone = true
dest = "{{ home_dir }}/workspace/other/nerd-fonts"
repo = "https://github.com/ryanoasis/nerd-fonts.git"

[[jobs]]
name = "nerd-fonts: install"
needs = ["nerd-fonts: repository"]
type = "command"
chdir = "{{ home_dir }}/workspace/other/nerd-fonts"
command = "bash"
argv = [
  "-c",
  './install.sh'
]


[[jobs]]
name = "set-up gtk theme"
type = "command"
chdir = "{{ home_dir }}/.dotfiles/gists"
command = "bash"
argv = [
  "-c",
  './install-solarized-theme.sh'
]
