[tools]
go = "1.26.2"
node = "25.9.0"
java = "adoptopenjdk-24.0.1+9"
awscli = "2.34.26"
direnv = "2.37.1"
lazygit = "0.56.0"
github-cli = "2.89.0"
usage = "3.2.0"
maven = "3.9.14"
yq = "4.52.5"
eza = "0.23.4"
dotnet = "10.0.201"
neovim = "0.12.1"
cmake = "4.3.1"
gradle = "9.4"
glab = { version = "1.91.0", exe = "glab" }

[settings]
fetch_remote_versions_cache = "365d"
always_keep_download = true
always_keep_install = true
plugin_autoupdate_last_check_duration = "365d"
quiet = true
