[tools]
go = "1.26.4"
node = "26.3.0"
java = "adoptopenjdk-24.0.1+9"
awscli = "2.34.53"
direnv = "2.37.1"
lazygit = "0.56.0"
github-cli = "2.94.0"
usage = "3.5.0"
maven = "3.9.16"
yq = "4.53.3"
eza = "0.23.4"
dotnet = "10.0.301"
neovim = "0.12.3"
cmake = "4.3.3"
gradle = "9.5"
glab = { version = "1.100.0", exe = "glab" }

[settings]
fetch_remote_versions_cache = "365d"
always_keep_download = true
always_keep_install = true
plugin_autoupdate_last_check_duration = "365d"
quiet = true
